amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: test1
    secretkey: test2
reset-tables: true
endpoints:
  beans:
    enabled: true
  autoconfig:
    enabled: false
  configprops:
    enabled: false
  dump:
    enabled: false
  env:
    enabled: false
  health:
    enabled: true
    path: /
  info:
    enabled: false
  metrics:
    enabled: false
  mappings:
    enabled: false
  shutdown:
    enabled: false
  trace:
    enabled: false

---
spring:
  profiles: container
amazon:
  dynamodb:
    endpoint: https://dynamodb.ca-central-1.amazonaws.com
  aws:
    accesskey: ${ACCESS_KEY}
    secretkey: ${SECRET_KEY}
reset-tables: ${DROP_DB}