FROM jenkins/jenkins:lts
USER root
RUN apt-get update 
RUN apt-get install -y maven nano sudo
RUN curl -fsSL get.docker.com -o get-docker.sh
RUN sh get-docker.sh
RUN usermod -aG docker jenkins
RUN service docker --full-restart
RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin