server:
  port: ${PORT:8080}
spring:
  datasource:
    jdbcUrl: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      ddl-auto: create-drop

endpoints:
  beans:
    enabled: true
  autoconfig:
    enabled: false
  configprops:
    enabled: false
  dump:
    enabled: false
  env:
    enabled: false
  health:
    enabled: true
    path: /health
  info:
    enabled: false
  metrics:
    enabled: false
  mappings:
    enabled: false
  shutdown:
    enabled: false
  trace:
    enabled: false
logging:
  level:
    root: INFO
  pattern:
    console: "${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: ./application.log
transactrules:
  batch:
    dayend:
      accountSetSize: 10
      concurentTasks: 4
---
spring:
  profiles: container
  datasource:
    jdbcUrl: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      dialect:  org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: create

---

spring.datasource:
    driverClassName:
    url:

spring:
  profiles: test
  datasource:
    jdbcUrl: jdbc:h2:mem:bootexample;MODE=MySQL
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      dialect:  org.hibernate.dialect.H2Dialect
      ddl-auto: create